config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items

  resources :collections


  namespace :api do
    scope :pages do
      get '/home', to: 'pages#home'
      get '/add', to: 'pages#add'
    end

    scope :search do
      get '/', to: 'search#find_all_where'
      get '/users/items', to: 'search#find_users_item'
    end

    scope :products do
      post '/add', to: 'products#add'
    end
  end

  get '/search', to: 'pages#index'
  get '/add', to: 'pages#add'

  get '*any', to: 'pages#not_found'
  root 'pages#index'
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_one :user
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :collection
  has_one :user, through: :collections

  fuzzily_searchable :name
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items, through: :collection
  has_one :collection
end

app/controllers/api/pages_controller.rb
class Api::PagesController < ApplicationController
  rescue_from ActionController::UnknownFormat, with: :raise_not_found

  def home
    items = current_user.items

    render json: { items: items }
  end

  def add
    render json: { }
  end

  def not_found
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404", layout: false, status: :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  def raise_not_found
    render file: "#{Rails.root}/public/404", layout: false, status: :not_found
  end

  private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
  rescue_from ActionController::UnknownFormat, with: :raise_not_found

  def add
    message = "failed to add item"
    state = "error"
    item = params[:item]

    collection = Collection.where(user_id: current_user.id).order(:created_at).first_or_create
    new_item = collection.items.new( name: item["ItemAttributes"]["Title"], image: item["LargeImage"]["URL"], amazon_url: item["DetailPageURL"], ASIN: item["ASIN"])

    if new_item.save
      message = "Added item succesfully"
      state = "ok"
    end


    render json: { message: message, state: state }
  end

  def not_found
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404", layout: false, status: :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  def raise_not_found
    render file: "#{Rails.root}/public/404", layout: false, status: :not_found
  end

  private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end
end

app/controllers/api/search_controller.rb
class Api::SearchController < ApplicationController
  respond_to :json

  def find_all_where
    page = params[:page] || "1"
    request = Vacuum.new

    request.configure(
      aws_access_key_id: ENV["S3_KEY_ID"],
      aws_secret_access_key: ENV["S3_SECRET"],
      associate_tag: "tag"
    )

    response = request.item_search(
      query: {
        'Keywords' => params[:search_term],
        'SearchIndex' => 'All',
        'ItemPage' => page
      }
    )

    items = []
    response.to_h["ItemSearchResponse"]["Items"]["Item"].each do |item|
      items.push(item_search(item["ASIN"]))
    end

    render json: { items: items, searchTerm: params[:search_term] }
  end

  def find_users_item
    items = Item.find_by_fuzzy_name(params[:search_term], :limit => 10)
    
    found_users_items = []
    users_items_ids = Item.joins(:collection).where('collections.user_id', current_user.id).pluck(:id)

    items.each do |item|
      if !users_items_ids.index(item.id).nil?
        found_users_items.push(item)
      end
    end

    render json: { items: found_users_items, searchTerm: params[:search_term] }
  end

  private

    def item_search(item_id)
      request = Vacuum.new

      request.configure(
        aws_access_key_id: ENV["S3_KEY_ID"],
        aws_secret_access_key: ENV["S3_SECRET"],
        associate_tag: "tag"
      )

      response = request.item_lookup(
        query: {
          'ItemId' => item_id,
          'ResponseGroup' => 'Small, Images'
        }
      )

      response.to_h["ItemLookupResponse"]["Items"]["Item"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  rescue_from ActionController::UnknownFormat, with: :raise_not_found
  rescue_from ActionView::MissingTemplate do render '/generic_page' end
  after_action :allow_iframe

  def index
    if user_signed_in?
      @whiteLogo = view_context.image_url("Vault-Web-White.svg")
      @component_name = "MySafe"
      @url = "/"
      @api_url = "/api/pages/home"
    else
      redirect_to '/users/sign_in'
    end
  end

  def add
    if user_signed_in?
      @whiteLogo = view_context.image_url("Vault-Web-White.svg")
      @component_name = "AddItemView"
      @url = "/add"
      @api_url = "/api/pages/add"
    else
      redirect_to '/users/sign_in'
    end
  end

  # def item
  #   @component_name = "MyItemView"
  #   @url = "/item/#{params[:id]}"
  #   @api_url = "/api/item/#{params[:id]}"
  # end

  def not_found
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404", layout: false, status: :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  def raise_not_found
    render file: "#{Rails.root}/public/404", layout: false, status: :not_found
  end

  private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Collections</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.user_id %></td>
        <td><%= collection.item_id %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @collection.user_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @collection.item_id %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :collection_id %><br>
    <%= f.number_field :collection_id %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br>
    <%= f.text_field :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :barcode %><br>
    <%= f.text_field :barcode %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br>
    <%= f.text_field :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :amazon_url %><br>
    <%= f.text_field :amazon_url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Collection</th>
      <th>Expiration date</th>
      <th>Image</th>
      <th>Barcode</th>
      <th>Expiration date</th>
      <th>Amazon url</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.collection_id %></td>
        <td><%= item.expiration_date %></td>
        <td><%= item.image %></td>
        <td><%= item.barcode %></td>
        <td><%= item.expiration_date %></td>
        <td><%= item.amazon_url %></td>
        <td><%= item.name %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Collection:</strong>
  <%= @item.collection_id %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @item.expiration_date %>
</p>

<p>
  <strong>Image:</strong>
  <%= @item.image %>
</p>

<p>
  <strong>Barcode:</strong>
  <%= @item.barcode %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @item.expiration_date %>
</p>

<p>
  <strong>Amazon url:</strong>
  <%= @item.amazon_url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_alert.html.erb
<% flash.each do |name, msg| -%>
  <div class="<%= name %> alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= msg %>
  </div>
<% end -%>

app/views/layouts/_meta.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<meta name="description" content="">
<meta name="revisit-after" content="30 days">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vault.io</title>
  <%= render 'layouts/meta' %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'modernizr' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
</body>
</html>